services:
  - type: web
    name: bluezygpt-web
    runtime: docker
    plan: free

  - type: worker
    name: bluezygpt-bot
    runtime: node
    plan: free
    rootDir: bot
    envVars:
      - key: DISCORD_TOKEN
        value: MTU1MTk1ODE2ODQwNDIzNDI4MA.Gl6sN3.EJVjdNHyU2d_IuWolCkvo9-8MpW6XZkAuszcz4
